// GENERATED by scripts/build-edge.mjs from packages/ai/src/schemas.ts. Do not edit.
// deno-lint-ignore-file
export const SCHEMAS = {
  "AiDraft": {
    "$defs": {
      "__schema0": {
        "type": "object",
        "properties": {
          "min": {
            "type": "number"
          },
          "max": {
            "type": "number"
          },
          "label": {
            "type": "string"
          },
          "color": {
            "type": "string",
            "description": "{enum: [\"teal\",\"amber\",\"magenta\",\"darkMagenta\",\"navy\",\"grey\"]}"
          },
          "summary": {
            "type": "string",
            "description": "One sentence under the tier name"
          },
          "body": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Optional guidance paragraph (Markdown; may use {{weakestSection}}, {{score}})"
          }
        },
        "additionalProperties": false,
        "required": [
          "min",
          "max",
          "label",
          "color",
          "summary",
          "body"
        ]
      }
    },
    "type": "object",
    "properties": {
      "title": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "productLine": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "intro": {
        "type": "object",
        "properties": {
          "eyebrow": {
            "type": "string"
          },
          "headline": {
            "type": "string"
          },
          "subheadline": {
            "type": "string"
          },
          "body": {
            "type": "string"
          },
          "bullets": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "startLabel": {
            "type": "string"
          },
          "estimatedMinutes": {
            "type": "number"
          }
        },
        "additionalProperties": false,
        "required": [
          "eyebrow",
          "headline",
          "subheadline",
          "body",
          "bullets",
          "startLabel",
          "estimatedMinutes"
        ]
      },
      "scoringMethod": {
        "type": "string",
        "description": "{enum: [\"points\",\"gaps\",\"none\"]}"
      },
      "tierBasis": {
        "type": "string",
        "description": "{enum: [\"percent\",\"points\"]}"
      },
      "display": {
        "type": "string",
        "description": "{enum: [\"percent\",\"points\"]}"
      },
      "sections": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "description": "Short unique key, e.g. \"s1\""
            },
            "name": {
              "type": "string"
            },
            "productIds": {
              "type": "array",
              "description": "IDs of provided products that solve this area (shown as \"Solved by\")",
              "items": {
                "type": "string"
              }
            },
            "showInResults": {
              "type": "boolean"
            }
          },
          "additionalProperties": false,
          "required": [
            "key",
            "name",
            "productIds",
            "showInResults"
          ]
        }
      },
      "questions": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "description": "Short unique key, e.g. \"q1\""
            },
            "sectionKey": {
              "type": "string"
            },
            "type": {
              "type": "string",
              "description": "{enum: [\"single\",\"multi\",\"dropdown\",\"yesno\",\"rating\",\"text\",\"longtext\"]}"
            },
            "role": {
              "type": "string",
              "description": "{enum: [\"scored\",\"gate\",\"segment\",\"info\"]}"
            },
            "text": {
              "type": "string"
            },
            "shortLabel": {
              "type": "string",
              "description": "2–5 word label used in reports and results, e.g. \"Denial tracking\""
            },
            "helpText": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ]
            },
            "required": {
              "type": "boolean"
            },
            "options": {
              "type": "array",
              "description": "Answer choices for single/multi/dropdown/yesno questions; empty for others",
              "items": {
                "type": "object",
                "properties": {
                  "label": {
                    "type": "string",
                    "description": "Answer text shown to the respondent"
                  },
                  "points": {
                    "anyOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "description": "Points for this answer when scoringMethod is \"points\"; null otherwise"
                  },
                  "isGap": {
                    "type": "boolean",
                    "description": "True when this answer reveals an operational gap"
                  },
                  "notApplicable": {
                    "type": "boolean",
                    "description": "On a gate question: marks the section not applicable. On a scored question: excludes it from scoring"
                  },
                  "allowOtherText": {
                    "type": "boolean",
                    "description": "True for an \"Other (please specify)\" answer"
                  },
                  "recommendProductId": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "description": "ID of a provided product that solves the need this answer reveals, or null"
                  },
                  "recommendBadge": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "description": "Short badge for the recommendation card, e.g. \"Top Priority\" or \"Opportunity\""
                  },
                  "recommendRank": {
                    "anyOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "description": "Lower ranks sort first (e.g. 0 for the worst answer, 5 for a partial answer)"
                  }
                },
                "additionalProperties": false,
                "required": [
                  "label",
                  "points",
                  "isGap",
                  "notApplicable",
                  "allowOtherText",
                  "recommendProductId",
                  "recommendBadge",
                  "recommendRank"
                ]
              }
            },
            "ratingMin": {
              "anyOf": [
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ]
            },
            "ratingMax": {
              "anyOf": [
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ]
            },
            "ratingMinLabel": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ]
            },
            "ratingMaxLabel": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ]
            },
            "showIfQuestionKey": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Only show this question when an EARLIER question has one of showIfOptionLabels selected"
            },
            "showIfOptionLabels": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "additionalProperties": false,
          "required": [
            "key",
            "sectionKey",
            "type",
            "role",
            "text",
            "shortLabel",
            "helpText",
            "required",
            "options",
            "ratingMin",
            "ratingMax",
            "ratingMinLabel",
            "ratingMaxLabel",
            "showIfQuestionKey",
            "showIfOptionLabels"
          ]
        }
      },
      "tiers": {
        "type": "array",
        "items": {
          "$ref": "#/$defs/__schema0"
        }
      },
      "sectionTiers": {
        "type": "array",
        "items": {
          "$ref": "#/$defs/__schema0"
        }
      },
      "insights": {
        "type": "array",
        "description": "Ordered guidance rules; the first match is shown. End with an \"always\" fallback",
        "items": {
          "type": "object",
          "properties": {
            "when": {
              "type": "string",
              "description": "{enum: [\"always\",\"sectionsBelowCount\",\"weakestInclude\",\"overallBetween\"]}"
            },
            "pct": {
              "anyOf": [
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ]
            },
            "atLeast": {
              "anyOf": [
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ]
            },
            "sectionKeys": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "topN": {
              "anyOf": [
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ]
            },
            "min": {
              "anyOf": [
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ]
            },
            "max": {
              "anyOf": [
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ]
            },
            "body": {
              "type": "string"
            }
          },
          "additionalProperties": false,
          "required": [
            "when",
            "pct",
            "atLeast",
            "sectionKeys",
            "topN",
            "min",
            "max",
            "body"
          ]
        }
      },
      "recommendations": {
        "type": "object",
        "properties": {
          "enabled": {
            "type": "boolean"
          },
          "heading": {
            "type": "string"
          },
          "intro": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "emptyMessage": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "additionalProperties": false,
        "required": [
          "enabled",
          "heading",
          "intro",
          "emptyMessage"
        ]
      },
      "leadCapture": {
        "type": "object",
        "properties": {
          "position": {
            "type": "string",
            "description": "{enum: [\"beforeResults\",\"beforeQuestions\",\"off\"]}"
          },
          "heading": {
            "type": "string"
          },
          "body": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "fieldKeys": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "{enum: [\"first_name\",\"last_name\",\"email\",\"organization\",\"job_title\",\"phone\",\"state\"]}"
            }
          },
          "requiredKeys": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "{enum: [\"first_name\",\"last_name\",\"email\",\"organization\",\"job_title\",\"phone\",\"state\"]}"
            }
          }
        },
        "additionalProperties": false,
        "required": [
          "position",
          "heading",
          "body",
          "fieldKeys",
          "requiredKeys"
        ]
      },
      "results": {
        "type": "object",
        "properties": {
          "eyebrow": {
            "type": "string"
          },
          "headline": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "body": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "showSectionBreakdown": {
            "type": "boolean"
          },
          "showGapList": {
            "type": "boolean"
          },
          "showInsights": {
            "type": "boolean"
          },
          "showRecommendations": {
            "type": "boolean"
          },
          "primaryCtaLabel": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "primaryCtaUrl": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "footerNote": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "thankYouHeadline": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "thankYouBody": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "additionalProperties": false,
        "required": [
          "eyebrow",
          "headline",
          "body",
          "showSectionBreakdown",
          "showGapList",
          "showInsights",
          "showRecommendations",
          "primaryCtaLabel",
          "primaryCtaUrl",
          "footerNote",
          "thankYouHeadline",
          "thankYouBody"
        ]
      },
      "designNotes": {
        "type": "string",
        "description": "2–4 sentences for the creator explaining the structure and scoring choices"
      }
    },
    "additionalProperties": false,
    "required": [
      "title",
      "description",
      "productLine",
      "intro",
      "scoringMethod",
      "tierBasis",
      "display",
      "sections",
      "questions",
      "tiers",
      "sectionTiers",
      "insights",
      "recommendations",
      "leadCapture",
      "results",
      "designNotes"
    ],
    "description": "{$schema: \"https://json-schema.org/draft/2020-12/schema\"}"
  },
  "RewriteResult": {
    "type": "object",
    "properties": {
      "alternatives": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "text": {
              "type": "string"
            },
            "shortLabel": {
              "type": "string"
            },
            "why": {
              "type": "string"
            }
          },
          "additionalProperties": false,
          "required": [
            "text",
            "shortLabel",
            "why"
          ]
        }
      }
    },
    "additionalProperties": false,
    "required": [
      "alternatives"
    ],
    "description": "{$schema: \"https://json-schema.org/draft/2020-12/schema\"}"
  },
  "OptionsResult": {
    "type": "object",
    "properties": {
      "options": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "label": {
              "type": "string"
            },
            "points": {
              "anyOf": [
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ]
            },
            "isGap": {
              "type": "boolean"
            },
            "notApplicable": {
              "type": "boolean"
            }
          },
          "additionalProperties": false,
          "required": [
            "label",
            "points",
            "isGap",
            "notApplicable"
          ]
        }
      },
      "rationale": {
        "type": "string"
      }
    },
    "additionalProperties": false,
    "required": [
      "options",
      "rationale"
    ],
    "description": "{$schema: \"https://json-schema.org/draft/2020-12/schema\"}"
  },
  "TierCopyResult": {
    "type": "object",
    "properties": {
      "tiers": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "label": {
              "type": "string"
            },
            "summary": {
              "type": "string"
            },
            "body": {
              "type": "string"
            }
          },
          "additionalProperties": false,
          "required": [
            "label",
            "summary",
            "body"
          ]
        }
      }
    },
    "additionalProperties": false,
    "required": [
      "tiers"
    ],
    "description": "{$schema: \"https://json-schema.org/draft/2020-12/schema\"}"
  },
  "ReviewResult": {
    "type": "object",
    "properties": {
      "overall": {
        "type": "string"
      },
      "issues": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "severity": {
              "type": "string",
              "description": "{enum: [\"high\",\"medium\",\"low\"]}"
            },
            "area": {
              "type": "string",
              "description": "{enum: [\"content\",\"scoring\",\"results\",\"lead\",\"branding\",\"other\"]}"
            },
            "questionNumber": {
              "anyOf": [
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ],
              "description": "1-based question number from the provided list, or null"
            },
            "message": {
              "type": "string"
            },
            "suggestion": {
              "type": "string"
            }
          },
          "additionalProperties": false,
          "required": [
            "severity",
            "area",
            "questionNumber",
            "message",
            "suggestion"
          ]
        }
      }
    },
    "additionalProperties": false,
    "required": [
      "overall",
      "issues"
    ],
    "description": "{$schema: \"https://json-schema.org/draft/2020-12/schema\"}"
  },
  "KnowledgeExtract": {
    "type": "object",
    "properties": {
      "title": {
        "type": "string"
      },
      "kind": {
        "type": "string",
        "description": "{enum: [\"product_info\",\"best_practices\",\"messaging\",\"reference\"]}"
      },
      "topic": {
        "type": "string"
      },
      "productLine": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "content": {
        "type": "string",
        "description": "Clean, well-structured Markdown notes capturing every useful fact"
      },
      "summary": {
        "type": "string"
      }
    },
    "additionalProperties": false,
    "required": [
      "title",
      "kind",
      "topic",
      "productLine",
      "content",
      "summary"
    ],
    "description": "{$schema: \"https://json-schema.org/draft/2020-12/schema\"}"
  }
} as const satisfies Record<string, Record<string, unknown>>;
