// Build the ai-assist Edge Function into ONE self-contained file that can be pasted
// into the Supabase dashboard (Edge Functions → ai-assist → Code).
//
//   node scripts/build-edge.mjs
//
// 1. Pre-computes the structured-output JSON schemas from packages/ai/src/schemas.ts
//    (using the Anthropic SDK's own zod converter), so the function needs no zod.
// 2. Bundles supabase/functions/ai-assist/src/index.ts + packages/ai prompts with esbuild,
//    rewriting npm packages to Deno `npm:` specifiers.
import { writeFileSync, readFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { build } from 'esbuild';
import { zodOutputFormat } from '@anthropic-ai/sdk/helpers/zod';
import * as S from '../packages/ai/src/schemas.ts';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const fnDir = join(root, 'supabase', 'functions', 'ai-assist');
const pkg = (name) => JSON.parse(readFileSync(join(root, 'node_modules', name, 'package.json'), 'utf8')).version;

// 1. Schemas
const schemas = {
  AiDraft: S.AiDraftSchema,
  RewriteResult: S.RewriteResultSchema,
  OptionsResult: S.OptionsResultSchema,
  TierCopyResult: S.TierCopyResultSchema,
  ReviewResult: S.ReviewResultSchema,
  KnowledgeExtract: S.KnowledgeExtractSchema,
};
const out = {};
for (const [k, v] of Object.entries(schemas)) out[k] = zodOutputFormat(v).schema;
writeFileSync(
  join(fnDir, 'src', 'generated-schemas.ts'),
  `// GENERATED by scripts/build-edge.mjs from packages/ai/src/schemas.ts. Do not edit.\n` +
    `// deno-lint-ignore-file\n` +
    `export const SCHEMAS = ${JSON.stringify(out, null, 2)} as const satisfies Record<string, Record<string, unknown>>;\n`,
);

// 2. Bundle
const npmMap = {
  '@anthropic-ai/sdk': `npm:@anthropic-ai/sdk@${pkg('@anthropic-ai/sdk')}`,
  '@supabase/supabase-js': `npm:@supabase/supabase-js@${pkg('@supabase/supabase-js')}`,
};
const denoNpm = {
  name: 'deno-npm',
  setup(b) {
    b.onResolve({ filter: /^[^./]/ }, (args) => {
      // Only bare package specifiers (skip the entry point and absolute Windows paths)
      if (args.kind === 'entry-point' || /^[a-zA-Z]:[\\/]/.test(args.path)) return undefined;
      const hit = Object.keys(npmMap).find((m) => args.path === m || args.path.startsWith(`${m}/`));
      if (!hit) return { errors: [{ text: `Unmapped package "${args.path}". Add it to npmMap in build-edge.mjs.` }] };
      return { path: npmMap[hit] + args.path.slice(hit.length), external: true };
    });
  },
};

const result = await build({
  entryPoints: [join(fnDir, 'src', 'index.ts')],
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  write: false,
  legalComments: 'none',
  plugins: [denoNpm],
  banner: {
    js:
      '// ─────────────────────────────────────────────────────────────────────────────\n' +
      '// GENERATED by `node scripts/build-edge.mjs`. Do not edit by hand.\n' +
      '// Source: supabase/functions/ai-assist/src/index.ts + packages/ai/src/*\n' +
      '// Deploy: Supabase → Edge Functions → ai-assist → paste this file → Deploy.\n' +
      '// Requires the ANTHROPIC_API_KEY secret. Keep "Verify JWT" ON.\n' +
      '// ─────────────────────────────────────────────────────────────────────────────',
  },
});
const file = join(fnDir, 'index.ts');
writeFileSync(file, result.outputFiles[0].text);
console.log(`Built ${file} (${Math.round(statSync(file).size / 1024)} KB)`);
